server:
  publicAddr: 0.0.0.0:9700
  privateAddr: 0.0.0.0:9701
  uploadTimeout: 30m # 上传URL有效时间
  downloadTimeout: 30m # 下载URL有效时间

db:
  type: mysql
  host: 47.109.79.103
  port: 3306
  user: root
  password: 12345678
  dbname: file_engine
  maxOpenConns: 10
  maxIdleConns: 5
  connMaxLifetime: 30m

minio:
  endpoint: 124.220.236.38:7001
  accessKey: admin
  secretKey: 1234567890
  bucketID: file-engine